# Generated by Django 4.0.1 on 2024-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('order_id', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
