# Generated by Django 4.0.1 on 2024-05-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='clothes_images/')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.producer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.style')),
            ],
        ),
    ]
