# Generated by Django 4.0.1 on 2024-05-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
