# Generated by Django 4.0.1 on 2024-05-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('product_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
            ],
        ),
    ]
