# Generated by Django 4.0.1 on 2024-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_type', models.CharField(max_length=20)),
                ('star', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
